apiVersion: rainbond.io/v1alpha1
kind: RbdComponent
metadata:
  name: rbd-etcd
  namespace: rbd-system
spec:
  image: registry.cn-hangzhou.aliyuncs.com/goodrain/etcd:v3.3.18
  priorityComponent: true
