apiVersion: rainbond.io/v1alpha1
kind: RbdComponent
metadata:
  name: rbd-eventlog
  namespace: rbd-system
spec:
  image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-eventlog:v5.5.0-release
  priorityComponent: true
